name: tabletennis
root_dir: /data/online_tt_dataset/matches
video_dirname: rallies_videos
frame_dirname: frames
csv_dirname: csv
train:
  matches : [ '00',
              '01',
              '02',
              '03',
              '04',
              '05',
              '06',
              '07',
              '08',
              '09',
              '10',
              '11',
              '12',
              '13',
              '13',
              '15',
              '16',
              '17',
              '18',
              '19',
              '20',
              '21']
  num_clip_ratio: 1.0
test:
  matches: [  '22',
              '23',
              '24',
              '25'   ]
  num_clip_ratio: 1.0
